version: '3.8'

services:

  app:
    build:
      context: .  # Set context to the root of your project to access all directories.
      dockerfile: ./apps/client/Dockerfile  # Specify Dockerfile location explicitly.
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:p8n2KcxzFeAB@ep-snowy-poetry-a5w65snc.us-east-2.aws.neon.tech/neondb?sslmode=require"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: p8n2KcxzFeAB  # Use a secure password in production!
      POSTGRES_DB: neondb 
    ports:
      - "5432:5432"
